name: ETL pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"
  
  workflow_dispatch:

jobs:
  ETL Railway Data Pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ETL script
        run: python -m src.etl

      - name: Upload CSV outputs
        uses: actions/upload-artifact@v4
        with:
          name: csv-outputs
          path: output/
